# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    -   id: pytest-test-runner
        name: pytest-test-runner
        language: system
        always_run: true
        entry: bash -c 'cd test-runner && pytest tests/utest.py -W ignore::UserWarning'
