name: Run triton test

on:
  push:
    branches: [ master ]
    paths:
      - 'clarifai/models/**'
  pull_request:
    paths:
      - 'clarifai/models/**'

jobs:
  triton-model-test:

    runs-on: ubuntu-latest
    container:
      image: nvcr.io/nvidia/tritonserver:23.03-py3
      options: --shm-size 2g
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r tests/requirements.txt
    - name: start triton
      run: |
        tritonserver --model-repository ./tests/dummy_triton_models --exit-on-error false &>/dev/null &
        python3 -m pytest tests/dummy_triton_models/_test_all_dummies.py -s
