version: '3'
services:
  pip-base:
    build:
      args: 
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ""
        BASE_IMAGE_NAME: ${BASE_IMAGE_NAME:-ubuntu}
        BASE_IMAGE_TAG: ${BASE_IMAGE_TAG:-22.04}
        PYTHON_VERSION: ${PYTHON_VERSION:-3.10}
      context: .
      target: pip
    command: >
      bash -c 'python --version'
    image: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pip-py${PYTHON_VERSION:-3.10}-base
    pull_policy: always

  idp-base:
    build:
      args:
        IDP_VERSION: ${IDP_VERSION:-core}
        MINICONDA_VERSION: ${MINICONDA_VERSION:-latest-Linux-x86_64}
      context: .
      target: idp
    command: >
      bash -c "conda env list"
    extends: pip-base
    image: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-idp-${IDP_VERSION:-core}-py${PYTHON_VERSION:-3.10}-base
